# Generated by Django 5.2.3 on 2025-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images', verbose_name='изображение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('is_publicated', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('views_counter', models.PositiveIntegerField(default=0, verbose_name='счетчик просмотров')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['name', 'created_at', 'is_publicated', 'views_counter'],
            },
        ),
    ]
